import type {
  Activity,
  AppNotification,
  AppState,
  BusinessProfile,
  CareCircleMember,
  SeniorBus,
  WeekItem,
} from "./types";

export const SENIOR = {
  id: "margaret",
  name: "Margaret Johnson",
  firstName: "Margaret",
  age: 72,
  neighborhood: "Oak Park",
  interests: ["Gardening", "Walking", "Yoga", "Museums"],
  accessibility: ["Walker", "Door-to-door assistance"],
  emergencyContact: "Sarah Johnson · Daughter",
};

export const FAMILY = {
  id: "sarah",
  name: "Sarah Johnson",
  firstName: "Sarah",
  relationship: "Daughter",
  city: "Austin",
};

export const CARE_CIRCLE: CareCircleMember[] = [
  {
    id: "sarah",
    name: "Sarah Johnson",
    relationship: "Daughter",
    city: "Austin",
    initials: "SJ",
    tone: "sage",
  },
  {
    id: "michael",
    name: "Michael Johnson",
    relationship: "Son",
    city: "Chicago",
    initials: "MJ",
    tone: "sky",
  },
  {
    id: "emily",
    name: "Emily Chen",
    relationship: "Caregiver",
    city: "Oak Park",
    initials: "EC",
    tone: "gold",
  },
];

export const CATEGORIES: { id: Activity["category"]; label: string; hint: string }[] = [
  { id: "fun", label: "Fun", hint: "Museums, movies, theater" },
  { id: "exercise", label: "Exercise", hint: "Yoga, swimming, walking" },
  { id: "social", label: "Social", hint: "Bingo, coffee, meetups" },
  { id: "outdoors", label: "Outdoors", hint: "Gardens, parks, trails" },
  { id: "shopping", label: "Shopping", hint: "Markets and stores" },
  { id: "healthcare", label: "Healthcare", hint: "Appointments and pharmacy" },
  { id: "errands", label: "Errands", hint: "Grocery, bank, salon" },
];

const DRIVER_JAMES = {
  name: "James Okonkwo",
  years: 6,
  vehicle: "Accessible van",
  plate: "EGO-102",
  photoInitials: "JO",
};

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: "garden-walk",
    name: "Senior Walking Group",
    summary: "Easy pace through the conservatory and outdoor gardens.",
    description:
      "A gentle walking group through the conservatory and outdoor gardens. Docents set an easy pace with plenty of benches. Plants, fresh air, and people who like both — Margaret's kind of afternoon.",
    businessId: "botanical-garden",
    businessName: "Botanical Garden",
    category: "outdoors",
    day: "Saturday",
    time: "1:00 PM",
    location: "Botanical Garden, Main Gate",
    neighborhood: "20 minutes from Oak Park",
    price: "Garden admission complimentary for the group",
    seniorDiscount: "Senior group rate included",
    accessibility: ["Paved paths", "Benches throughout", "Step-free restrooms"],
    attendeeCount: 8,
    spots: 12,
    featured: true,
    hasTransport: true,
    busId: "bus-102",
  },
  {
    id: "senior-yoga",
    name: "Senior Yoga",
    summary: "Chair-friendly yoga with a familiar instructor.",
    description:
      "A Tuesday morning class designed for stiff joints and curious minds. Chairs available, no floor work required, and tea after class.",
    businessId: "oak-community",
    businessName: "Oak Park Community Center",
    category: "exercise",
    day: "Tuesday",
    time: "9:30 AM",
    location: "Community Center, Studio B",
    neighborhood: "Oak Park",
    price: "$6",
    accessibility: ["Elevator", "Chairs provided"],
    attendeeCount: 11,
    spots: 16,
    hasTransport: true,
    busId: "bus-88",
  },
  {
    id: "museum-tour",
    name: "Art Museum Docent Tour",
    summary: "A small-group tour of the impressionist wing.",
    description:
      "A Friday docent tour with seating in every gallery. Headphones and large-print guides available.",
    businessId: "city-museum",
    businessName: "City Art Museum",
    category: "fun",
    day: "Friday",
    time: "2:00 PM",
    location: "City Art Museum",
    neighborhood: "Downtown",
    price: "$8 senior ticket",
    seniorDiscount: "$4 off general admission",
    accessibility: ["Wheelchair accessible", "Seating in galleries"],
    attendeeCount: 6,
    spots: 10,
    hasTransport: true,
    busId: "bus-41",
  },
  {
    id: "ymca-aerobics",
    name: "Senior Water Aerobics",
    summary: "Warm-pool class at the YMCA.",
    description:
      "A Wednesday water aerobics class in the warm pool. Instructors stay in the water, and the YMCA has pool lifts.",
    businessId: "ymca",
    businessName: "YMCA",
    category: "exercise",
    day: "Wednesday",
    time: "10:00 AM",
    location: "YMCA, Aquatic Center",
    neighborhood: "15 minutes from Oak Park",
    price: "$5",
    accessibility: ["Pool lift", "Locker room bench seating"],
    attendeeCount: 14,
    spots: 20,
    hasTransport: true,
    busId: "bus-12",
  },
  {
    id: "community-garden",
    name: "Community Garden Morning",
    summary: "Potting, watering, and a slow walk between beds.",
    description:
      "Monday mornings in the community plots. Raised beds, shared tools, and lemonade at 10:30.",
    businessId: "community-garden",
    businessName: "Oak Park Community Garden",
    category: "outdoors",
    day: "Monday",
    time: "9:00 AM",
    location: "Community Garden, Maple Street",
    neighborhood: "Oak Park",
    price: "Free",
    accessibility: ["Raised beds", "Packed gravel paths"],
    attendeeCount: 9,
    spots: 15,
    hasTransport: false,
  },
  {
    id: "friday-bingo",
    name: "Friday Bingo",
    summary: "Classic bingo night with supper first.",
    description:
      "Supper at 5:15, bingo at 6:00. Large-print cards and a prize table that takes itself seriously.",
    businessId: "senior-center",
    businessName: "Oak Park Senior Center",
    category: "social",
    day: "Friday",
    time: "6:00 PM",
    location: "Senior Center, Main Hall",
    neighborhood: "Oak Park",
    price: "$3 for cards",
    accessibility: ["Ground floor", "Hearing loop"],
    attendeeCount: 22,
    spots: 40,
    hasTransport: false,
  },
  {
    id: "coffee-group",
    name: "Tuesday Coffee Group",
    summary: "A standing coffee date for regulars and newcomers.",
    description:
      "No agenda. Just coffee, a large-print crossword, and people who will save Margaret a seat.",
    businessId: "maple-cafe",
    businessName: "Maple Cafe",
    category: "social",
    day: "Tuesday",
    time: "10:00 AM",
    location: "Maple Cafe",
    neighborhood: "Oak Park",
    price: "Pay for your coffee",
    accessibility: ["Street-level entrance"],
    attendeeCount: 7,
    spots: 12,
    hasTransport: false,
  },
  {
    id: "pharmacy-stop",
    name: "Pharmacy & checkup shuttle",
    summary: "A slower Thursday stop at the clinic and pharmacy.",
    description:
      "Drop-off at the neighborhood clinic, then the pharmacy next door. Drivers wait, and the van has a walker-friendly step.",
    businessId: "oak-clinic",
    businessName: "Oak Park Clinic",
    category: "healthcare",
    day: "Thursday",
    time: "9:00 AM",
    location: "Oak Park Clinic",
    neighborhood: "Oak Park",
    price: "$6 round trip",
    accessibility: ["Walker-friendly step", "Door-to-door assistance"],
    attendeeCount: 4,
    spots: 8,
    hasTransport: true,
    busId: "bus-7",
  },
  {
    id: "farmers-market",
    name: "Saturday farmers market",
    summary: "Stalls, flowers, and a bench-friendly loop.",
    description:
      "A short market loop with time to sit. Volunteers can carry bags back to the Senior Bus.",
    businessId: "oak-market",
    businessName: "Oak Park Market",
    category: "shopping",
    day: "Saturday",
    time: "9:30 AM",
    location: "Oak Park Market Square",
    neighborhood: "Oak Park",
    price: "Free to attend",
    accessibility: ["Paved paths", "Help with bags"],
    attendeeCount: 10,
    spots: 16,
    hasTransport: false,
  },
  {
    id: "grocery-shuttle",
    name: "Grocery & Errands Shuttle",
    summary: "A shared Thursday run to the market and pharmacy.",
    description:
      "Door-to-door help with bags. The shuttle waits at the market, then stops at the pharmacy on the way home.",
    businessId: "evergo-errands",
    businessName: "EverGo Errands",
    category: "errands",
    day: "Thursday",
    time: "11:00 AM",
    location: "Oak Park Market",
    neighborhood: "Oak Park",
    price: "$7 round trip",
    accessibility: ["Door-to-door assistance", "Help with bags"],
    attendeeCount: 5,
    spots: 8,
    hasTransport: true,
    busId: "bus-7",
  },
];

export const INITIAL_BUSES: SeniorBus[] = [
  {
    id: "bus-102",
    number: "102",
    activityId: "garden-walk",
    destination: "Botanical Garden",
    pickupTime: "12:15 PM",
    returnTime: "3:00 PM",
    capacity: 12,
    booked: 8,
    driver: DRIVER_JAMES,
  },
  {
    id: "bus-88",
    number: "88",
    activityId: "senior-yoga",
    destination: "Oak Park Community Center",
    pickupTime: "8:50 AM",
    returnTime: "11:00 AM",
    capacity: 10,
    booked: 7,
    driver: {
      name: "Priya Shah",
      years: 4,
      vehicle: "Accessible van",
      plate: "EGO-088",
      photoInitials: "PS",
    },
  },
  {
    id: "bus-41",
    number: "41",
    activityId: "museum-tour",
    destination: "City Art Museum",
    pickupTime: "1:10 PM",
    returnTime: "4:30 PM",
    capacity: 10,
    booked: 6,
    driver: {
      name: "Luis Ramirez",
      years: 8,
      vehicle: "Accessible van",
      plate: "EGO-041",
      photoInitials: "LR",
    },
  },
  {
    id: "bus-12",
    number: "12",
    activityId: "ymca-aerobics",
    destination: "YMCA",
    pickupTime: "9:15 AM",
    returnTime: "11:30 AM",
    capacity: 12,
    booked: 9,
    driver: DRIVER_JAMES,
  },
  {
    id: "bus-7",
    number: "7",
    activityId: "grocery-shuttle",
    destination: "Oak Park Market",
    pickupTime: "10:40 AM",
    returnTime: "12:45 PM",
    capacity: 8,
    booked: 5,
    driver: {
      name: "Priya Shah",
      years: 4,
      vehicle: "Accessible van",
      plate: "EGO-007",
      photoInitials: "PS",
    },
  },
];

export const INITIAL_WEEK: WeekItem[] = [
  {
    day: "Tue",
    weekday: "Tuesday",
    label: "Senior Yoga",
    activityId: "senior-yoga",
    tone: "gold",
    status: "completed",
  },
  {
    day: "Fri",
    weekday: "Friday",
    label: "Museum",
    activityId: "museum-tour",
    tone: "sky",
    status: "completed",
  },
  {
    day: "Sat",
    weekday: "Saturday",
    label: "Botanical Garden",
    activityId: "garden-walk",
    tone: "sage",
    status: "recommended",
  },
];

export const INITIAL_BUSINESSES: BusinessProfile[] = [
  {
    id: "botanical-garden",
    name: "Botanical Garden",
    kind: "Gardens & outdoors",
    visitorsThisWeek: 42,
    transportBookings: 17,
    repeatVisitorsPct: 31,
  },
  {
    id: "ymca",
    name: "YMCA",
    kind: "Fitness",
    visitorsThisWeek: 68,
    transportBookings: 24,
    repeatVisitorsPct: 44,
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: "n-museum",
    title: "Margaret arrived safely.",
    body: "Friday's museum tour wrapped up without a hitch.",
    timeLabel: "Yesterday",
    unread: false,
  },
  {
    id: "n-yoga",
    title: "Margaret is home.",
    body: "Tuesday Senior Yoga is complete.",
    timeLabel: "Tue",
    unread: false,
  },
];

export function createInitialState(): AppState {
  return {
    role: "family",
    activities: INITIAL_ACTIVITIES,
    buses: INITIAL_BUSES,
    bookings: [
      {
        id: "b-yoga",
        activityId: "senior-yoga",
        busId: "bus-88",
        seniorId: SENIOR.id,
        bookedBy: FAMILY.name,
        createdLabel: "Last week",
      },
      {
        id: "b-museum",
        activityId: "museum-tour",
        busId: "bus-41",
        seniorId: SENIOR.id,
        bookedBy: FAMILY.name,
        createdLabel: "Monday",
      },
    ],
    notifications: INITIAL_NOTIFICATIONS,
    week: INITIAL_WEEK,
    businesses: INITIAL_BUSINESSES,
    trip: null,
    demoClock: "Saturday · 12:10 PM",
    toast: null,
  };
}

export const TRIP_ORDER = [
  "scheduled",
  "driver_arriving",
  "picked_up",
  "in_transit",
  "arrived",
  "returning",
  "completed",
] as const;

export const TRIP_COPY: Record<
  (typeof TRIP_ORDER)[number],
  { label: string; clock: string; title: string; body: string }
> = {
  scheduled: {
    label: "Confirmed",
    clock: "Saturday · 12:10 PM",
    title: "Trip confirmed",
    body: "Senior Bus #102 will pick Margaret up at 12:15 PM.",
  },
  driver_arriving: {
    label: "Driver arriving",
    clock: "Saturday · 12:12 PM",
    title: "Margaret's driver is arriving.",
    body: "Senior Bus #102 is a few minutes from home.",
  },
  picked_up: {
    label: "Picked up",
    clock: "Saturday · 12:16 PM",
    title: "Margaret has been picked up.",
    body: "She is on Senior Bus #102 with James.",
  },
  in_transit: {
    label: "In transit",
    clock: "Saturday · 12:28 PM",
    title: "Margaret is on the way to the Botanical Garden.",
    body: "Estimated arrival 12:50 PM.",
  },
  arrived: {
    label: "Arrived",
    clock: "Saturday · 12:52 PM",
    title: "Margaret arrived safely.",
    body: "She is at the Botanical Garden Senior Walking Group.",
  },
  returning: {
    label: "Returning",
    clock: "Saturday · 3:05 PM",
    title: "Margaret is heading home.",
    body: "Return trip on Senior Bus #102.",
  },
  completed: {
    label: "Completed",
    clock: "Saturday · 3:40 PM",
    title: "Margaret is home.",
    body: "The trip is complete.",
  },
};
